import "@radix-ui/themes/styles.css";
import "./theme-config.css"
import type { Metadata } from "next";
import { Inter,Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { Theme } from "@radix-ui/themes";

const inter = Inter({
  subsets : ['latin'],
  variable: '--font-inter',
})

// const geistSans = Geist({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}`}
      >
        <Theme accentColor="violet">
          <Navbar />
          <main className="p-5">{children}</main>
        
        </Theme>
      </body>
    </html>
  );
}
